FROM debian:buster-20210408

RUN apt update && apt install -y php7.2 \
  php-zip \
  php-dom \
  php-opcache \
  php-pdo \
  php-calendar \
  php-ctype \
  php-curl \
  php-exif \
  php-fileinfo \
  php-ftp \
  php-gettext \
  php-iconv \
  php-json \
  php-mbstring \
  php-phar \
  php-posix \
  php-readline \
  php-shmop \
  php-sockets \
  php-sysvmsg \
  php-sysvsem \
  php-sysvshm \
  php-tokenizer
