FROM debian:buster-20210408

RUN apt update && apt install -y php7.3 \
  php7.3-zip \
  php7.3-dom \
  php7.3-opcache \
  php7.3-pdo \
  php7.3-calendar \
  php7.3-ctype \
  php7.3-curl \
  php7.3-exif \
  php7.3-fileinfo \
  php7.3-ftp \
  php7.3-gettext \
  php7.3-iconv \
  php7.3-json \
  php7.3-mbstring \
  php7.3-phar \
  php7.3-posix \
  php7.3-readline \
  php7.3-shmop \
  php7.3-sockets \
  php7.3-sysvmsg \
  php7.3-sysvsem \
  php7.3-sysvshm \
  php7.3-tokenizer
